package notice;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map.Entry;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.commons.codec.digest.DigestUtils;

import tools.ExecShell;
import tools.JobConfig;
import tools.MySQL;
import tools.ParseDate;
import tools.SysFunc;
import tools.TimeUtils;
import tools.WriteJobStatus; 

public class CourtNoticeType1Job {
	
	String startDt=TimeUtils.getYesterday();
	String stopDt=TimeUtils.getToday();
	String tableId="27";
	static Pattern pattern2 = Pattern.compile("[(\\d+)]{4}年[(\\d+)]{1,2}月[(\\d+)]{1,3}日");
	Pattern pattern = Pattern.compile("申请再审人|原审\\(一审\\)诉讼地位|抗诉机关|诉讼|反诉|被申诉人|申诉人|再审|申请人|原审|被上诉人|上诉人|被告人|原告|被告|公诉方|第三人|被|等");
	static HashMap<String,String> courtCity=new HashMap<String,String>(); 
	static
	{
		courtCity.put("东源县人民法院","河源市");
		courtCity.put("东莞市第一人民法院","东莞市");
		courtCity.put("东莞市第三人民法院","东莞市");
		courtCity.put("东莞市第二人民法院","东莞市");
		courtCity.put("中山市第一人民法院","中山市");
		courtCity.put("中山市第二人民法院","中山市");
		courtCity.put("丰顺县人民法院","梅州市");
		courtCity.put("乐昌市人民法院","韶关市");
		courtCity.put("乳源瑶族自治县人民法院","韶关市");
		courtCity.put("云浮市云城区人民法院","云浮市");
		courtCity.put("云浮市云安区人民法院","云浮市");
		courtCity.put("五华县人民法院","梅州市");
		courtCity.put("仁化县人民法院","韶关市");
		courtCity.put("从化市人民法院","广州市");
		courtCity.put("佛冈县人民法院","清远市");
		courtCity.put("佛山市三水区人民法院","佛山市");
		courtCity.put("佛山市南海区人民法院","佛山市");
		courtCity.put("佛山市禅城区人民法院","佛山市");
		courtCity.put("佛山市顺德区人民法院","佛山市");
		courtCity.put("佛山市高明区人民法院","佛山市");
		courtCity.put("信宜市人民法院","茂名市");
		courtCity.put("兴宁市人民法院","梅州市");
		courtCity.put("前海合作区人民法院","深圳市");
		courtCity.put("化州市人民法院","茂名市");
		courtCity.put("南澳县人民法院","汕头市");
		courtCity.put("南雄市人民法院","韶关市");
		courtCity.put("博罗县人民法院","惠州市");
		courtCity.put("台山市人民法院","江门市");
		courtCity.put("吴川市人民法院","湛江市");
		courtCity.put("和平县人民法院","河源市");
		courtCity.put("四会市人民法院","肇庆市");
		courtCity.put("增城市人民法院","广州市");
		courtCity.put("大埔县人民法院","梅州市");
		courtCity.put("始兴县人民法院","韶关市");
		courtCity.put("封开县人民法院","肇庆市");
		courtCity.put("平远县人民法院","梅州市");
		courtCity.put("广东省东莞市中级人民法院","东莞市");
		courtCity.put("广东省中山市中级人民法院","中山市");
		courtCity.put("广东省云浮市中级人民法院","云浮市");
		courtCity.put("广东省佛山市中级人民法院","佛山市");
		courtCity.put("广东省广州市中级人民法院","广州市");
		courtCity.put("广东省惠州市中级人民法院","惠州市");
		courtCity.put("广东省揭阳市中级人民法院","揭阳市");
		courtCity.put("广东省梅州市中级人民法院","梅州市");
		courtCity.put("广东省汕头市中级人民法院","汕头市");
		courtCity.put("广东省汕尾市中级人民法院","汕尾市");
		courtCity.put("广东省江门市中级人民法院","江门市");
		courtCity.put("广东省河源市中级人民法院","河源市");
		courtCity.put("广东省深圳市中级人民法院","深圳市");
		courtCity.put("广东省清远市中级人民法院","清远市");
		courtCity.put("广东省湛江市中级人民法院","湛江市");
		courtCity.put("广东省潮州市中级人民法院","潮州市");
		courtCity.put("广东省珠海市中级人民法院","珠海市");
		courtCity.put("广东省肇庆市中级人民法院","肇庆市");
		courtCity.put("广东省茂名市中级人民法院","茂名市");
		courtCity.put("广东省阳江市中级人民法院","阳江市");
		courtCity.put("广东省韶关市中级人民法院","韶关市");
		courtCity.put("广东省高级人民法院","广州市");
		courtCity.put("广宁县人民法院","肇庆市");
		courtCity.put("广州市南沙区人民法院","广州市");
		courtCity.put("广州市天河区人民法院","广州市");
		courtCity.put("广州市海珠区人民法院","广州市");
		courtCity.put("广州市番禺区人民法院","广州市");
		courtCity.put("广州市白云区人民法院","广州市");
		courtCity.put("广州市花都区人民法院","广州市");
		courtCity.put("广州市荔湾区人民法院","广州市");
		courtCity.put("广州市萝岗区人民法院","广州市");
		courtCity.put("广州市越秀区人民法院","广州市");
		courtCity.put("广州市黄埔区人民法院","广州市");
		courtCity.put("广州海事法院","广州市");
		courtCity.put("广州知识产权法院","广州市");
		courtCity.put("广州铁路运输中级法院","广州市");
		courtCity.put("广州铁路运输法院","广州市");
		courtCity.put("廉江市人民法院","湛江市");
		courtCity.put("开平市人民法院","江门市");
		courtCity.put("徐闻县人民法院","湛江市");
		courtCity.put("德庆县人民法院","肇庆市");
		courtCity.put("怀集县人民法院","肇庆市");
		courtCity.put("恩平市人民法院","江门市");
		courtCity.put("惠东县人民法院","惠州市");
		courtCity.put("惠州市大亚湾经济技术开发区人民法院","惠州市");
		courtCity.put("惠州市惠城区人民法院","惠州市");
		courtCity.put("惠州市惠阳区人民法院","惠州市");
		courtCity.put("惠来县人民法院","揭阳市");
		courtCity.put("揭西县人民法院","揭阳市");
		courtCity.put("揭阳市揭东区人民法院","揭阳市");
		courtCity.put("揭阳市榕城区人民法院","揭阳市");
		courtCity.put("新丰县人民法院","韶关市");
		courtCity.put("新兴县人民法院","云浮市");
		courtCity.put("普宁市人民法院","揭阳市");
		courtCity.put("梅州市梅县区人民法院","梅州市");
		courtCity.put("梅州市梅江区人民法院","梅州市");
		courtCity.put("汕头市潮南区人民法院","汕头市");
		courtCity.put("汕头市潮阳区人民法院","汕头市");
		courtCity.put("汕头市澄海区人民法院","汕头市");
		courtCity.put("汕头市濠江区人民法院","汕头市");
		courtCity.put("汕头市金平区人民法院","汕头市");
		courtCity.put("汕头市龙湖区人民法院","汕头市");
		courtCity.put("汕尾市城区人民法院","汕尾市");
		courtCity.put("江门市新会区人民法院","江门市");
		courtCity.put("江门市江海区人民法院","江门市");
		courtCity.put("江门市蓬江区人民法院","江门市");
		courtCity.put("河源市源城区人民法院","河源市");
		courtCity.put("海丰县人民法院","汕尾市");
		courtCity.put("深圳市南山区人民法院","深圳市");
		courtCity.put("深圳市宝安区人民法院","深圳市");
		courtCity.put("深圳市盐田区人民法院","深圳市");
		courtCity.put("深圳市福田区人民法院","深圳市");
		courtCity.put("深圳市罗湖区人民法院","深圳市");
		courtCity.put("深圳市龙岗区人民法院","深圳市");
		courtCity.put("清远市清城区人民法院","清远市");
		courtCity.put("清远市清新区人民法院","清远市");
		courtCity.put("湛江市坡头区人民法院","湛江市");
		courtCity.put("湛江市赤坎区人民法院","湛江市");
		courtCity.put("湛江市霞山区人民法院","湛江市");
		courtCity.put("湛江市麻章区人民法院","湛江市");
		courtCity.put("湛江经济技术开发区人民法院","湛江市");
		courtCity.put("潮州市枫溪人民法院","潮州市");
		courtCity.put("潮州市湘桥区人民法院","潮州市");
		courtCity.put("潮州市潮安区人民法院","潮州市");
		courtCity.put("珠海市斗门区人民法院","珠海市");
		courtCity.put("珠海市金湾区人民法院","珠海市");
		courtCity.put("珠海市香州区人民法院","珠海市");
		courtCity.put("珠海横琴新区人民法院","珠海市");
		courtCity.put("紫金县人民法院","河源市");
		courtCity.put("罗定市人民法院","云浮市");
		courtCity.put("翁源县人民法院","韶关市");
		courtCity.put("肇庆市端州区人民法院","肇庆市");
		courtCity.put("肇庆市鼎湖区人民法院","肇庆市");
		courtCity.put("肇庆铁路运输法院","广州市");
		courtCity.put("英德市人民法院","清远市");
		courtCity.put("茂名市电白区人民法院","茂名市");
		courtCity.put("茂名市茂南区人民法院","茂名市");
		courtCity.put("蕉岭县人民法院","梅州市");
		courtCity.put("连南瑶族自治县人民法院","清远市");
		courtCity.put("连山壮族瑶族自治县人民法院","清远市");
		courtCity.put("连州市人民法院","清远市");
		courtCity.put("连平县人民法院","河源市");
		courtCity.put("遂溪县人民法院","湛江市");
		courtCity.put("郁南县人民法院","云浮市");
		courtCity.put("阳山县人民法院","清远市");
		courtCity.put("阳春市人民法院","阳江市");
		courtCity.put("阳江市江城区人民法院","阳江市");
		courtCity.put("阳江市阳东区人民法院","阳江市");
		courtCity.put("阳西县人民法院","阳江市");
		courtCity.put("陆丰市人民法院","汕尾市");
		courtCity.put("陆河县人民法院","汕尾市");
		courtCity.put("雷州市人民法院","湛江市");
		courtCity.put("韶关市曲江区人民法院","韶关市");
		courtCity.put("韶关市武江区人民法院","韶关市");
		courtCity.put("韶关市浈江区人民法院","韶关市");
		courtCity.put("饶平县人民法院","潮州市");
		courtCity.put("高州市人民法院","茂名市");
		courtCity.put("高要市人民法院","肇庆市");
		courtCity.put("鹤山市人民法院","江门市");
		courtCity.put("龙川县人民法院","河源市");
		courtCity.put("龙门县人民法院","惠州市");
		courtCity.put("东平县人民法院","泰安市");
		courtCity.put("东明县人民法院","菏泽市");
		courtCity.put("菏泽市定陶区人民法院","菏泽市");
		courtCity.put("东营市东营区人民法院","东营市");
		courtCity.put("东营市河口区人民法院","东营市");
		courtCity.put("东营经济技术开发区人民法院","东营市");
		courtCity.put("东阿县人民法院","聊城市");
		courtCity.put("临朐县人民法院","潍坊市");
		courtCity.put("临沂市兰山区人民法院","临沂市");
		courtCity.put("临沂市河东区人民法院","临沂市");
		courtCity.put("临沂市罗庄区人民法院","临沂市");
		courtCity.put("临沂经济技术开发区人民法院","临沂市");
		courtCity.put("临沂高新技术产业开发区人民法院","临沂市");
		courtCity.put("临沭县人民法院","临沂市");
		courtCity.put("临清市人民法院","聊城市");
		courtCity.put("临邑县人民法院","德州市");
		courtCity.put("德州经济技术开发区人民法院","德州市");
		courtCity.put("乐陵市人民法院","德州市");
		courtCity.put("乳山市人民法院","威海市");
		courtCity.put("五莲县人民法院","日照市");
		courtCity.put("兰陵县人民法院","临沂市");
		courtCity.put("冠县人民法院","聊城市");
		courtCity.put("利津县人民法院","东营市");
		courtCity.put("单县人民法院","菏泽市");
		courtCity.put("博兴县人民法院","滨州市");
		courtCity.put("即墨市人民法院","青岛市");
		courtCity.put("商河县人民法院","济南市");
		courtCity.put("嘉祥县人民法院","济宁市");
		courtCity.put("垦利县人民法院","东营市");
		courtCity.put("夏津县人民法院","德州市");
		courtCity.put("威海市文登区人民法院","威海市");
		courtCity.put("威海市环翠区人民法院","威海市");
		courtCity.put("威海火炬高技术产业开发区人民法院","威海市");
		courtCity.put("威海经济技术开发区人民法院","威海市");
		courtCity.put("宁津县人民法院","德州市");
		courtCity.put("宁阳县人民法院","泰安市");
		courtCity.put("安丘市人民法院","潍坊市");
		courtCity.put("定陶县人民法院","菏泽市");
		courtCity.put("寿光市人民法院","潍坊市");
		courtCity.put("山东省东营市中级人民法院","东营市");
		courtCity.put("山东省临沂市中级人民法院","临沂市");
		courtCity.put("山东省威海市中级人民法院","威海市");
		courtCity.put("山东省德州市中级人民法院","德州市");
		courtCity.put("山东省日照市中级人民法院","日照市");
		courtCity.put("山东省枣庄市中级人民法院","枣庄市");
		courtCity.put("山东省泰安市中级人民法院","泰安市");
		courtCity.put("山东省济南市中级人民法院","济南市");
		courtCity.put("山东省济宁市中级人民法院","济宁市");
		courtCity.put("山东省淄博市中级人民法院","淄博市");
		courtCity.put("山东省滨州市中级人民法院","滨州市");
		courtCity.put("山东省潍坊市中级人民法院","潍坊市");
		courtCity.put("山东省烟台市中级人民法院","烟台市");
		courtCity.put("山东省聊城市中级人民法院","聊城市");
		courtCity.put("山东省莱芜市中级人民法院","莱芜市");
		courtCity.put("山东省菏泽市中级人民法院","菏泽市");
		courtCity.put("山东省青岛市中级人民法院","青岛市");
		courtCity.put("山东省高级人民法院","济南市");
		courtCity.put("济宁市中级人民法院","济宁市");
		courtCity.put("巨野县人民法院","菏泽市");
		courtCity.put("平原县人民法院","德州市");
		courtCity.put("平度市人民法院","青岛市");
		courtCity.put("平邑县人民法院","临沂市");
		courtCity.put("平阴县人民法院","济南市");
		courtCity.put("广饶县人民法院","东营市");
		courtCity.put("庆云县人民法院","德州市");
		courtCity.put("微山县人民法院","济宁市");
		courtCity.put("德州市德城区人民法院","德州市");
		courtCity.put("德州市陵城区人民法院","德州市");
		courtCity.put("德州经济开发区人民法院","德州市");
		courtCity.put("惠民县人民法院","滨州市");
		courtCity.put("成武县人民法院","菏泽市");
		courtCity.put("招远市人民法院","烟台市");
		courtCity.put("新泰市人民法院","泰安市");
		courtCity.put("无棣县人民法院","滨州市");
		courtCity.put("日照市东港区人民法院","日照市");
		courtCity.put("日照市岚山区人民法院","日照市");
		courtCity.put("日照经济技术开发区人民法院","日照市");
		courtCity.put("昌乐县人民法院","潍坊市");
		courtCity.put("昌邑市人民法院","潍坊市");
		courtCity.put("曲阜市人民法院","济宁市");
		courtCity.put("曹县人民法院","菏泽市");
		courtCity.put("枣庄市台儿庄区人民法院","枣庄市");
		courtCity.put("枣庄市山亭区人民法院","枣庄市");
		courtCity.put("枣庄市峄城区人民法院","枣庄市");
		courtCity.put("枣庄市市中区人民法院","枣庄市");
		courtCity.put("枣庄市薛城区人民法院","枣庄市");
		courtCity.put("栖霞市人民法院","烟台市");
		courtCity.put("桓台县人民法院","淄博市");
		courtCity.put("梁山县人民法院","济宁市");
		courtCity.put("武城县人民法院","德州市");
		courtCity.put("汶上县人民法院","济宁市");
		courtCity.put("沂南县人民法院","临沂市");
		courtCity.put("沂水县人民法院","临沂市");
		courtCity.put("沂源县人民法院","淄博市");
		courtCity.put("泗水县人民法院","济宁市");
		courtCity.put("泰安市岱岳区人民法院","泰安市");
		courtCity.put("泰安市泰山区人民法院","泰安市");
		courtCity.put("泰安高新技术产业开发区人民法院","泰安市");
		courtCity.put("济南市历下区人民法院","济南市");
		courtCity.put("济南市历城区人民法院","济南市");
		courtCity.put("济南市天桥区人民法院","济南市");
		courtCity.put("济南市市中区人民法院","济南市");
		courtCity.put("济南市槐荫区人民法院","济南市");
		courtCity.put("济南市长清区人民法院","济南市");
		courtCity.put("济南铁路运输中级法院","济南市");
		courtCity.put("济南铁路运输法院","济南市");
		courtCity.put("济南高新技术产业开发区人民法院","济南市");
		courtCity.put("济宁市任城区人民法院","济宁市");
		courtCity.put("济宁市兖州区人民法院","济宁市");
		courtCity.put("济宁高新技术产业开发区人民法院","济宁市");
		courtCity.put("济阳县人民法院","济南市");
		courtCity.put("海阳市人民法院","烟台市");
		courtCity.put("淄博市临淄区人民法院","淄博市");
		courtCity.put("淄博市博山区人民法院","淄博市");
		courtCity.put("淄博市周村区人民法院","淄博市");
		courtCity.put("淄博市张店区人民法院","淄博市");
		courtCity.put("淄博市淄川区人民法院","淄博市");
		courtCity.put("淄博市高新技术产业开发区人民法院","淄博市");
		courtCity.put("滕州市人民法院","枣庄市");
		courtCity.put("滨州市沾化区人民法院","滨州市");
		courtCity.put("滨州市滨城区人民法院","滨州市");
		courtCity.put("滨州经济技术开发区人民法院","滨州市");
		courtCity.put("潍坊市坊子区人民法院","潍坊市");
		courtCity.put("潍坊市奎文区人民法院","潍坊市");
		courtCity.put("潍坊市寒亭区人民法院","潍坊市");
		courtCity.put("潍坊市潍城区人民法院","潍坊市");
		courtCity.put("潍坊滨海经济技术开发区人民法院","潍坊市");
		courtCity.put("潍坊高新技术产业开发区人民法院","潍坊市");
		courtCity.put("烟台市牟平区人民法院","烟台市");
		courtCity.put("烟台市福山区人民法院","烟台市");
		courtCity.put("烟台市芝罘区人民法院","烟台市");
		courtCity.put("烟台市莱山区人民法院","烟台市");
		courtCity.put("烟台经济技术开发区人民法院","烟台市");
		courtCity.put("烟台高新技术产业开发区人民法院","烟台市");
		courtCity.put("禹城市人民法院","德州市");
		courtCity.put("章丘市人民法院","济南市");
		courtCity.put("聊城市东昌府区人民法院","聊城市");
		courtCity.put("聊城经济技术开发区人民法院","聊城市");
		courtCity.put("肥城市人民法院","泰安市");
		courtCity.put("胶州市人民法院","青岛市");
		courtCity.put("茌平县人民法院","聊城市");
		courtCity.put("荣成市人民法院","威海市");
		courtCity.put("莒南县人民法院","临沂市");
		courtCity.put("莒县人民法院","日照市");
		courtCity.put("莘县人民法院","聊城市");
		courtCity.put("莱州市人民法院","烟台市");
		courtCity.put("莱芜市莱城区人民法院","莱芜市");
		courtCity.put("莱芜市钢城区人民法院","莱芜市");
		courtCity.put("莱西市人民法院","青岛市");
		courtCity.put("莱阳市人民法院","烟台市");
		courtCity.put("菏泽市牡丹区人民法院","菏泽市");
		courtCity.put("菏泽经济开发区人民法院","菏泽市");
		courtCity.put("蒙阴县人民法院","临沂市");
		courtCity.put("蓬莱市人民法院","烟台市");
		courtCity.put("诸城市人民法院","潍坊市");
		courtCity.put("费县人民法院","临沂市");
		courtCity.put("邹城市人民法院","济宁市");
		courtCity.put("邹平县人民法院","滨州市");
		courtCity.put("郓城县人民法院","菏泽市");
		courtCity.put("郯城县人民法院","临沂市");
		courtCity.put("鄄城县人民法院","菏泽市");
		courtCity.put("金乡县人民法院","济宁市");
		courtCity.put("长岛县人民法院","烟台市");
		courtCity.put("阳信县人民法院","滨州市");
		courtCity.put("阳谷县人民法院","聊城市");
		courtCity.put("青岛市城阳区人民法院","青岛市");
		courtCity.put("青岛市崂山区人民法院","青岛市");
		courtCity.put("青岛市市北区人民法院","青岛市");
		courtCity.put("青岛市市南区人民法院","青岛市");
		courtCity.put("青岛市李沧区人民法院","青岛市");
		courtCity.put("青岛市黄岛区人民法院","青岛市");
		courtCity.put("青岛海事法院","青岛市");
		courtCity.put("青岛铁路运输法院","济南市");
		courtCity.put("青州市人民法院","潍坊市");
		courtCity.put("高唐县人民法院","聊城市");
		courtCity.put("高密市人民法院","潍坊市");
		courtCity.put("高青县人民法院","淄博市");
		courtCity.put("鱼台县人民法院","济宁市");
		courtCity.put("齐河县人民法院","德州市");
		courtCity.put("龙口市人民法院","烟台市");
		courtCity.put("三门县人民法院","台州市");
		courtCity.put("东阳市人民法院","金华市");
		courtCity.put("临安市人民法院","杭州市");
		courtCity.put("临海市人民法院","台州市");
		courtCity.put("丽水市莲都区人民法院","丽水市");
		courtCity.put("义乌市人民法院","金华市");
		courtCity.put("乐清市人民法院","温州市");
		courtCity.put("云和县人民法院","丽水市");
		courtCity.put("仙居县人民法院","台州市");
		courtCity.put("余姚市人民法院","宁波市");
		courtCity.put("兰溪市人民法院","金华市");
		courtCity.put("台州市椒江区人民法院","台州市");
		courtCity.put("台州市路桥区人民法院","台州市");
		courtCity.put("台州市黄岩区人民法院","台州市");
		courtCity.put("嘉兴市南湖区人民法院","嘉兴市");
		courtCity.put("嘉兴市秀洲区人民法院","嘉兴市");
		courtCity.put("嘉善县人民法院","嘉兴市");
		courtCity.put("天台县人民法院","台州市");
		courtCity.put("奉化市人民法院","宁波市");
		courtCity.put("宁波市北仑区人民法院","宁波市");
		courtCity.put("宁波市江东区人民法院","宁波市");
		courtCity.put("宁波市江北区人民法院","宁波市");
		courtCity.put("宁波市海曙区人民法院","宁波市");
		courtCity.put("宁波市鄞州区人民法院","宁波市");
		courtCity.put("宁波市镇海区人民法院","宁波市");
		courtCity.put("宁波海事法院","宁波市");
		courtCity.put("宁海县人民法院","宁波市");
		courtCity.put("安吉县人民法院","湖州市");
		courtCity.put("岱山县人民法院","舟山市");
		courtCity.put("嵊州市人民法院","绍兴市");
		courtCity.put("嵊泗县人民法院","舟山市");
		courtCity.put("常山县人民法院","衢州市");
		courtCity.put("平湖市人民法院","嘉兴市");
		courtCity.put("平阳县人民法院","温州市");
		courtCity.put("庆元县人民法院","丽水市");
		courtCity.put("建德市人民法院","杭州市");
		courtCity.put("开化县人民法院","衢州市");
		courtCity.put("德清县人民法院","湖州市");
		courtCity.put("慈溪市人民法院","宁波市");
		courtCity.put("文成县人民法院","温州市");
		courtCity.put("新昌县人民法院","绍兴市");
		courtCity.put("景宁畲族自治县人民法院","丽水市");
		courtCity.put("杭州市上城区人民法院","杭州市");
		courtCity.put("杭州市下城区人民法院","杭州市");
		courtCity.put("杭州市余杭区人民法院","杭州市");
		courtCity.put("杭州市富阳区人民法院","杭州市");
		courtCity.put("杭州市拱墅区人民法院","杭州市");
		courtCity.put("杭州市江干区人民法院","杭州市");
		courtCity.put("杭州市滨江区人民法院","杭州市");
		courtCity.put("杭州市萧山区人民法院","杭州市");
		courtCity.put("杭州市西湖区人民法院","杭州市");
		courtCity.put("杭州经济技术开发区人民法院","杭州市");
		courtCity.put("杭州铁路运输法院","杭州市");
		courtCity.put("松阳县人民法院","丽水市");
		courtCity.put("桐乡市人民法院","嘉兴市");
		courtCity.put("桐庐县人民法院","杭州市");
		courtCity.put("武义县人民法院","金华市");
		courtCity.put("永嘉县人民法院","温州市");
		courtCity.put("永康市人民法院","金华市");
		courtCity.put("江山市人民法院","衢州市");
		courtCity.put("泰顺县人民法院","温州市");
		courtCity.put("洞头县人民法院","温州市");
		courtCity.put("浙江省丽水市中级人民法院","丽水市");
		courtCity.put("浙江省台州市中级人民法院","台州市");
		courtCity.put("浙江省嘉兴市中级人民法院","嘉兴市");
		courtCity.put("浙江省宁波市中级人民法院","宁波市");
		courtCity.put("浙江省杭州市中级人民法院","杭州市");
		courtCity.put("浙江省温州市中级人民法院","温州市");
		courtCity.put("浙江省湖州市中级人民法院","湖州市");
		courtCity.put("浙江省绍兴市中级人民法院","绍兴市");
		courtCity.put("浙江省舟山市中级人民法院","舟山市");
		courtCity.put("浙江省衢州市中级人民法院","衢州市");
		courtCity.put("浙江省金华市中级人民法院","金华市");
		courtCity.put("浙江省高级人民法院","杭州市");
		courtCity.put("浦江县人民法院","金华市");
		courtCity.put("海宁市人民法院","嘉兴市");
		courtCity.put("海盐县人民法院","嘉兴市");
		courtCity.put("淳安县人民法院","杭州市");
		courtCity.put("温岭市人民法院","台州市");
		courtCity.put("温州市瓯海区人民法院","温州市");
		courtCity.put("温州市鹿城区人民法院","温州市");
		courtCity.put("温州市龙湾区人民法院","温州市");
		courtCity.put("湖州市南浔区人民法院","湖州市");
		courtCity.put("湖州市吴兴区人民法院","湖州市");
		courtCity.put("玉环县人民法院","台州市");
		courtCity.put("瑞安市人民法院","温州市");
		courtCity.put("磐安县人民法院","金华市");
		courtCity.put("绍兴市上虞区人民法院","绍兴市");
		courtCity.put("绍兴市柯桥区人民法院","绍兴市");
		courtCity.put("绍兴市越城区人民法院","绍兴市");
		courtCity.put("缙云县人民法院","丽水市");
		courtCity.put("舟山市定海区人民法院","舟山市");
		courtCity.put("舟山市普陀区人民法院","舟山市");
		courtCity.put("苍南县人民法院","温州市");
		courtCity.put("衢州市柯城区人民法院","衢州市");
		courtCity.put("衢州市衢江区人民法院","衢州市");
		courtCity.put("诸暨市人民法院","绍兴市");
		courtCity.put("象山县人民法院","宁波市");
		courtCity.put("遂昌县人民法院","丽水市");
		courtCity.put("金华市婺城区人民法院","金华市");
		courtCity.put("金华市金东区人民法院","金华市");
		courtCity.put("长兴县人民法院","湖州市");
		courtCity.put("青田县人民法院","丽水市");
		courtCity.put("龙泉市人民法院","丽水市");
		courtCity.put("龙游县人民法院","衢州市");
		courtCity.put("杭州市中级人民法院","杭州市");
		courtCity.put("宁波市中级人民法院","宁波市");
		courtCity.put("嘉兴市中级人民法院","嘉兴市");
		courtCity.put("湖州市中级人民法院","湖州市");
		courtCity.put("绍兴市中级人民法院","绍兴市");
		courtCity.put("金华市中级人民法院","金华市");
		courtCity.put("衢州市中级人民法院","衢州市");
		courtCity.put("台州市中级人民法院","台州市");
		courtCity.put("舟山市中级人民法院","舟山市");
		courtCity.put("河源市中级人民法院","河源市");
		courtCity.put("深圳前海合作区人民法院","深圳市");
		courtCity.put("湛江市中级人民法院","湛江市");
		courtCity.put("聊城市中级人民法院","聊城市");
		courtCity.put("茂名市中级人民法院","茂名市");
		courtCity.put("青岛市中级人民法院","青岛市");
		courtCity.put("云浮市中级人民法院","云浮市");
		courtCity.put("德州市中级人民法院","德州市");
		courtCity.put("惠州市中级人民法院","惠州市");
		courtCity.put("景宁县人民法院","丽水市");
		courtCity.put("枣庄市中级人民法院","枣庄市");
		courtCity.put("深圳市中级人民法院","深圳市");
		courtCity.put("温州市中级人民法院","温州市");
		courtCity.put("温州市洞头区人民法院","温州市");
		courtCity.put("潍坊市中级人民法院","潍坊市");
		courtCity.put("潮州市中级人民法院","潮州市");
		courtCity.put("菏泽市中级人民法院","菏泽市");
		courtCity.put("临沂市中级人民法院","临沂市");
		courtCity.put("丽水市中级人民法院","丽水市");
		courtCity.put("广州铁路运输第一法院","广州市");
		courtCity.put("滨州市中级人民法院","滨州市");
		courtCity.put("石家庄铁路运输法院","石家庄市");
		courtCity.put("肇庆市中级人民法院","肇庆市");
		courtCity.put("莱芜市中级人民法院","莱芜市");
		courtCity.put("阳江市中级人民法院","阳江市");
		courtCity.put("韶关市中级人民法院","韶关市");
		courtCity.put("威海市中级人民法院","威海市");
		courtCity.put("山东省芜市中级人民法院","莱芜市");
		courtCity.put("广州铁路运输第二法院","广州市");
		courtCity.put("惠阳区人民法院","惠州市");
		courtCity.put("梅州市中级人民法院","梅州市");
		courtCity.put("济南市中级人民法院","济南市");
		courtCity.put("清远市中级人民法院","清远市");
		courtCity.put("烟台市中级人民法院","烟台市");
		courtCity.put("东营市中级人民法院","东营市");
		courtCity.put("中山市中级人民法院","中山市");
		courtCity.put("佛山市中级人民法院","佛山市");
		courtCity.put("揭阳市中级人民法院","揭阳市");
		courtCity.put("汕头市中级人民法院","汕头市");
		courtCity.put("泰安市中级人民法院","泰安市");
		courtCity.put("淄博市中级人民法院","淄博市");
		courtCity.put("淄博高新技术产业开发区人民法院","淄博市");
		courtCity.put("珠海市中级人民法院","珠海市");
		courtCity.put("珠海市香洲区人民法院","珠海市");
		courtCity.put("肇庆市高要区人民法院","肇庆市");
		courtCity.put("福建省高级人民法院","福州市");
		courtCity.put("广州市增城区人民法院","广州市");
		courtCity.put("广州市从化区人民法院","广州市");
		courtCity.put("广州南沙区人民法院","广州市");
		courtCity.put("日照市中级人民法院","日照市");
		courtCity.put("广州市中级人民法院","广州市");
		courtCity.put("东莞市中级人民法院","东莞市");
		courtCity.put("汕尾市中级人民法院","汕尾市");
		courtCity.put("揭东区人民法院","揭阳市");
		courtCity.put("江门市中级人民法院","江门市");
		courtCity.put("东营市垦利区人民法院","东营市");
		courtCity.put("垦利区人民法院","东营市");
		courtCity.put("济南市章丘区人民法院","济南市");
		courtCity.put("东兴","内江市");
		courtCity.put("北川","绵阳市");
		courtCity.put("安县","绵阳市");
		courtCity.put("高院","成都市");
		courtCity.put("广汉","德阳市");
		courtCity.put("锦江","成都市");
		courtCity.put("武侯","成都市");
		courtCity.put("成华","成都市");
		courtCity.put("新都","成都市");
		courtCity.put("金堂","成都市");
		courtCity.put("双流","成都市");
		courtCity.put("都江堰","成都市");
		courtCity.put("邛崃","成都市");
		courtCity.put("成都高新技术产业开发","成都市");
		courtCity.put("成都","成都市");
		courtCity.put("东区","攀枝花市");
		courtCity.put("江阳","泸州市");
		courtCity.put("合江","泸州市");
		courtCity.put("叙永","泸州市");
		courtCity.put("古蔺","泸州市");
		courtCity.put("旌阳","德阳市");
		courtCity.put("中江","德阳市");
		courtCity.put("什邡","德阳市");
		courtCity.put("绵竹","德阳市");
		courtCity.put("三台","绵阳市");
		courtCity.put("江油","绵阳市");
		courtCity.put("苍溪","广元市");
		courtCity.put("船山","遂宁市");
		courtCity.put("市中","内江市");
		courtCity.put("威远","内江市");
		courtCity.put("资中","内江市");
		courtCity.put("隆昌","内江市");
		courtCity.put("峨眉山","乐山市");
		courtCity.put("顺庆","南充市");
		courtCity.put("高坪","南充市");
		courtCity.put("嘉陵","南充市");
		courtCity.put("南部","南充市");
		courtCity.put("西充","南充市");
		courtCity.put("南充","南充市");
		courtCity.put("仁寿","眉山市");
		courtCity.put("广安","广安市");
		courtCity.put("广安","广安市");
		courtCity.put("岳池","广安市");
		courtCity.put("邻水","广安市");
		courtCity.put("大竹","达州市");
		courtCity.put("渠县","达州市");
		courtCity.put("万源","达州市");
		courtCity.put("雨城","雅安市");
		courtCity.put("巴州","巴州区");
		courtCity.put("雁江","资阳市");
		courtCity.put("安岳","资阳市");
		courtCity.put("西昌","凉山彝族自治州");
		courtCity.put("会理","凉山彝族自治州");
		courtCity.put("青羊","成都市");
		courtCity.put("金牛","成都市");
		courtCity.put("龙泉驿","成都市");
		courtCity.put("青白江","成都市");
		courtCity.put("温江","成都市");
		courtCity.put("郫县","成都市");
		courtCity.put("大邑","成都市");
		courtCity.put("蒲江","成都市");
		courtCity.put("新津","成都市");
		courtCity.put("简阳","资阳市");
		courtCity.put("彭州","成都市");
		courtCity.put("崇州","成都市");
		courtCity.put("自贡","自贡市");
		courtCity.put("西区","攀枝花市");
		courtCity.put("仁和","攀枝花市");
		courtCity.put("米易","攀枝花市");
		courtCity.put("盐边","攀枝花市");
		courtCity.put("攀枝花","攀枝花市");
		courtCity.put("纳溪","泸州市");
		courtCity.put("龙马潭","泸州市");
		courtCity.put("泸州","泸州市");
		courtCity.put("罗江","德阳市");
		courtCity.put("德阳","德阳市");
		courtCity.put("涪城","绵阳市");
		courtCity.put("游仙","绵阳市");
		courtCity.put("盐亭","绵阳市");
		courtCity.put("梓潼","绵阳市");
		courtCity.put("平武","绵阳市");
		courtCity.put("高新技术产业开","绵阳市");
		courtCity.put("绵阳","绵阳市");
		courtCity.put("利州","广元市");
		courtCity.put("元坝","广元市");
		courtCity.put("朝天","广元市");
		courtCity.put("旺苍","广元市");
		courtCity.put("青川","广元市");
		courtCity.put("剑阁","广元市");
		courtCity.put("广元","广元市");
		courtCity.put("安居","遂宁市");
		courtCity.put("蓬溪","遂宁市");
		courtCity.put("射洪","遂宁市");
		courtCity.put("大英","遂宁市");
		courtCity.put("遂宁","遂宁市");
		courtCity.put("内江","内江市");
		courtCity.put("沙湾","乐山市");
		courtCity.put("五通桥","乐山市");
		courtCity.put("金口河","乐山市");
		courtCity.put("犍为","乐山市");
		courtCity.put("井研","乐山市");
		courtCity.put("夹江","乐山市");
		courtCity.put("沐川","乐山市");
		courtCity.put("峨边彝族","乐山市");
		courtCity.put("马边彝族","乐山市");
		courtCity.put("乐山","乐山市");
		courtCity.put("营山","南充市");
		courtCity.put("蓬安","南充市");
		courtCity.put("仪陇","南充市");
		courtCity.put("阆中","南充市");
		courtCity.put("东坡","眉山市");
		courtCity.put("彭山","眉山市");
		courtCity.put("洪雅","眉山市");
		courtCity.put("眉山","眉山市");
		courtCity.put("翠屏","宜宾市");
		courtCity.put("南溪区","宜宾市");
		courtCity.put("宜宾","宜宾市");
		courtCity.put("宜宾","宜宾市");
		courtCity.put("江安","宜宾市");
		courtCity.put("长宁","宜宾市");
		courtCity.put("高县","宜宾市");
		courtCity.put("珙县","宜宾市");
		courtCity.put("筠连","宜宾市");
		courtCity.put("兴文","宜宾市");
		courtCity.put("屏山","宜宾市");
		courtCity.put("前锋","广安市");
		courtCity.put("武胜","广安市");
		courtCity.put("华蓥","广安市");
		courtCity.put("通川","达州市");
		courtCity.put("达","达州市");
		courtCity.put("宣汉","达州市");
		courtCity.put("开江","达州市");
		courtCity.put("达州","达州市");
		courtCity.put("名山","雅安市");
		courtCity.put("荥经","雅安市");
		courtCity.put("汉源","雅安市");
		courtCity.put("石棉","雅安市");
		courtCity.put("天全","雅安市");
		courtCity.put("芦山","雅安市");
		courtCity.put("宝兴","雅安市");
		courtCity.put("雅安","雅安市");
		courtCity.put("恩阳","巴中市");
		courtCity.put("通江","巴中市");
		courtCity.put("南江","巴中市");
		courtCity.put("平昌","巴中市");
		courtCity.put("巴中","巴中市");
		courtCity.put("乐至","资阳市");
		courtCity.put("资阳","资阳市");
		courtCity.put("马尔康","阿坝藏族羌族自治州");
		courtCity.put("汶川","阿坝藏族羌族自治州");
		courtCity.put("理县","阿坝藏族羌族自治州");
		courtCity.put("茂县","阿坝藏族羌族自治州");
		courtCity.put("松潘","阿坝藏族羌族自治州");
		courtCity.put("九寨沟","阿坝藏族羌族自治州");
		courtCity.put("金川","阿坝藏族羌族自治州");
		courtCity.put("小金","阿坝藏族羌族自治州");
		courtCity.put("黑水","阿坝藏族羌族自治州");
		courtCity.put("壤塘","阿坝藏族羌族自治州");
		courtCity.put("阿坝","阿坝藏族羌族自治州");
		courtCity.put("阿坝","阿坝藏族羌族自治州");
		courtCity.put("若尔盖","阿坝藏族羌族自治州");
		courtCity.put("红原","阿坝藏族羌族自治州");
		courtCity.put("康定","甘孜藏族自治州");
		courtCity.put("泸定","甘孜藏族自治州");
		courtCity.put("丹巴","甘孜藏族自治州");
		courtCity.put("九龙","甘孜藏族自治州");
		courtCity.put("雅江","甘孜藏族自治州");
		courtCity.put("道孚","甘孜藏族自治州");
		courtCity.put("炉霍","甘孜藏族自治州");
		courtCity.put("甘孜","甘孜藏族自治州");
		courtCity.put("德格","甘孜藏族自治州");
		courtCity.put("白玉","甘孜藏族自治州");
		courtCity.put("色达","甘孜藏族自治州");
		courtCity.put("理塘","甘孜藏族自治州");
		courtCity.put("巴塘","甘孜藏族自治州");
		courtCity.put("乡城","甘孜藏族自治州");
		courtCity.put("稻城","甘孜藏族自治州");
		courtCity.put("得荣","甘孜藏族自治州");
		courtCity.put("新龙","甘孜藏族自治州");
		courtCity.put("石渠","甘孜藏族自治州");
		courtCity.put("木里藏族","凉山彝族自治州");
		courtCity.put("盐源","凉山彝族自治州");
		courtCity.put("德昌","凉山彝族自治州");
		courtCity.put("会东","凉山彝族自治州");
		courtCity.put("宁南","凉山彝族自治州");
		courtCity.put("普格","凉山彝族自治州");
		courtCity.put("布拖","凉山彝族自治州");
		courtCity.put("金阳","凉山彝族自治州");
		courtCity.put("昭觉","凉山彝族自治州");
		courtCity.put("喜德","凉山彝族自治州");
		courtCity.put("冕宁","凉山彝族自治州");
		courtCity.put("越西","凉山彝族自治州");
		courtCity.put("甘洛","凉山彝族自治州");
		courtCity.put("美姑","凉山彝族自治州");
		courtCity.put("雷波","凉山彝族自治州");
		courtCity.put("凉山","凉山彝族自治州");
		courtCity.put("成都铁路","成都市");
		courtCity.put("西昌铁路","成都市");
		courtCity.put("成铁","成都市");
		courtCity.put("514003","贵阳市");
		courtCity.put("四川省高级人民法院","成都市");
		courtCity.put("泸县","泸州市");
		courtCity.put("","绵阳市");
		courtCity.put("湖北省高级人民法院","武汉市");
		courtCity.put("湖北省武汉市中级人民法院","武汉市");
		courtCity.put("武汉市中级人民法院","武汉市");
		courtCity.put("武汉市江岸区人民法院","武汉市");
		courtCity.put("武汉市江汉区人民法院","武汉市");
		courtCity.put("武汉市硚口区人民法院","武汉市");
		courtCity.put("武汉市汉阳区人民法院","武汉市");
		courtCity.put("武汉市武昌区人民法院","武汉市");
		courtCity.put("武汉市青山区人民法院","武汉市");
		courtCity.put("武汉市洪山区人民法院","武汉市");
		courtCity.put("武汉市东西湖区人民法院","武汉市");
		courtCity.put("武汉市汉南区人民法院","武汉市");
		courtCity.put("武汉市蔡甸区人民法院","武汉市");
		courtCity.put("武汉市江夏区人民法院","武汉市");
		courtCity.put("武汉市黄陂区人民法院","武汉市");
		courtCity.put("武汉市新洲区人民法院","武汉市");
		courtCity.put("武汉经济技术开发区人民法院","武汉市");
		courtCity.put("武汉东湖新技术开发区人民法院","武汉市");
		courtCity.put("湖北省黄石市中级人民法院","黄石市");
		courtCity.put("黄石市黄石港区人民法院","黄石市");
		courtCity.put("黄石市西塞山区人民法院","黄石市");
		courtCity.put("黄石市下陆区人民法院","黄石市");
		courtCity.put("黄石市铁山区人民法院","黄石市");
		courtCity.put("阳新县人民法院","黄石市");
		courtCity.put("大冶市人民法院","黄石市");
		courtCity.put("湖北省十堰市中级人民法院","十堰市");
		courtCity.put("十堰市茅箭区人民法院","十堰市");
		courtCity.put("十堰市张湾区人民法院","十堰市");
		courtCity.put("十堰市郧阳区人民法院","十堰市");
		courtCity.put("郧西县人民法院","十堰市");
		courtCity.put("竹山县人民法院","十堰市");
		courtCity.put("竹溪县人民法院","十堰市");
		courtCity.put("房县人民法院","十堰市");
		courtCity.put("丹江口市人民法院","十堰市");
		courtCity.put("湖北省宜昌市中级人民法院","宜昌市");
		courtCity.put("宜昌市中级人民法院","宜昌市");
		courtCity.put("宜昌市西陵区人民法院","宜昌市");
		courtCity.put("宜昌市伍家岗区人民法院","宜昌市");
		courtCity.put("宜昌市点军区人民法院","宜昌市");
		courtCity.put("宜昌市猇亭区人民法院","宜昌市");
		courtCity.put("宜昌市夷陵区人民法院","宜昌市");
		courtCity.put("远安县人民法院","宜昌市");
		courtCity.put("兴山县人民法院","宜昌市");
		courtCity.put("秭归县人民法院","宜昌市");
		courtCity.put("长阳土家族自治县人民法院","宜昌市");
		courtCity.put("五峰土家族自治县人民法院","宜昌市");
		courtCity.put("宜都市人民法院","宜昌市");
		courtCity.put("当阳市人民法院","宜昌市");
		courtCity.put("枝江市人民法院","宜昌市");
		courtCity.put("神农架林区人民法院","宜昌市");
		courtCity.put("宜昌市三峡坝区人民法院","宜昌市");
		courtCity.put("葛洲坝人民法院","宜昌市");
		courtCity.put("湖北省襄阳市中级人民法院","襄阳市");
		courtCity.put("襄阳市中级人民法院","襄阳市");
		courtCity.put("襄阳市襄城区人民法院","襄阳市");
		courtCity.put("襄阳市樊城区人民法院","襄阳市");
		courtCity.put("襄阳市襄州区人民法院","襄阳市");
		courtCity.put("南漳县人民法院","襄阳市");
		courtCity.put("谷城县人民法院","襄阳市");
		courtCity.put("保康县人民法院","襄阳市");
		courtCity.put("老河口市人民法院","襄阳市");
		courtCity.put("枣阳市人民法院","襄阳市");
		courtCity.put("宜城市人民法院","襄阳市");
		courtCity.put("襄阳高新技术产业开发区人民法院","襄阳市");
		courtCity.put("湖北省鄂州市中级人民法院","鄂州市");
		courtCity.put("鄂州市中级人民法院","鄂州市");
		courtCity.put("鄂州市梁子湖区人民法院","鄂州市");
		courtCity.put("鄂州市华容区人民法院","鄂州市");
		courtCity.put("鄂州市鄂城区人民法院","鄂州市");
		courtCity.put("湖北省荆门市中级人民法院","荆门市");
		courtCity.put("荆门市中级人民法院","荆门市");
		courtCity.put("荆门市东宝区人民法院","荆门市");
		courtCity.put("荆门市掇刀区人民法院","荆门市");
		courtCity.put("京山县人民法院","荆门市");
		courtCity.put("沙洋县人民法院","荆门市");
		courtCity.put("钟祥市人民法院","荆门市");
		courtCity.put("湖北省孝感市中级人民法院","孝感市");
		courtCity.put("孝感市中级人民法院","孝感市");
		courtCity.put("孝感市孝南区人民法院","孝感市");
		courtCity.put("孝昌县人民法院","孝感市");
		courtCity.put("大悟县人民法院","孝感市");
		courtCity.put("云梦县人民法院","孝感市");
		courtCity.put("应城市人民法院","孝感市");
		courtCity.put("安陆市人民法院","孝感市");
		courtCity.put("汉川市人民法院","孝感市");
		courtCity.put("湖北省荆州市中级人民法院","荆州市");
		courtCity.put("荆州市中级人民法院","荆州市");
		courtCity.put("荆州市沙市区人民法院","荆州市");
		courtCity.put("荆州市荆州区人民法院","荆州市");
		courtCity.put("公安县人民法院","荆州市");
		courtCity.put("监利县人民法院","荆州市");
		courtCity.put("江陵县人民法院","荆州市");
		courtCity.put("石首市人民法院","荆州市");
		courtCity.put("洪湖市人民法院","荆州市");
		courtCity.put("松滋市人民法院","荆州市");
		courtCity.put("湖北省黄冈市中级人民法院","黄冈市");
		courtCity.put("黄冈市中级人民法院","黄冈市");
		courtCity.put("黄冈市黄州区人民法院","黄冈市");
		courtCity.put("团风县人民法院","黄冈市");
		courtCity.put("红安县人民法院","黄冈市");
		courtCity.put("罗田县人民法院","黄冈市");
		courtCity.put("英山县人民法院","黄冈市");
		courtCity.put("浠水县人民法院","黄冈市");
		courtCity.put("蕲春县人民法院","黄冈市");
		courtCity.put("黄梅县人民法院","黄冈市");
		courtCity.put("麻城市人民法院","黄冈市");
		courtCity.put("武穴市人民法院","黄冈市");
		courtCity.put("湖北省咸宁市中级人民法院","咸宁市");
		courtCity.put("咸宁市中级人民法院","咸宁市");
		courtCity.put("咸宁市咸安区人民法院","咸宁市");
		courtCity.put("嘉鱼县人民法院","咸宁市");
		courtCity.put("通城县人民法院","咸宁市");
		courtCity.put("崇阳县人民法院","咸宁市");
		courtCity.put("通山县人民法院","咸宁市");
		courtCity.put("赤壁市人民法院","咸宁市");
		courtCity.put("湖北省随州市中级人民法院","随州市");
		courtCity.put("随州市中级人民法院","随州市");
		courtCity.put("随州市曾都区人民法院","随州市");
		courtCity.put("随县人民法院","随州市");
		courtCity.put("湖北省广水市人民法院","随州市");
		courtCity.put("湖北省恩施土家族苗族自治州中级人民法院","恩施土家族苗族自治州");
		courtCity.put("恩施土家族苗族自治州中级人民法院","恩施土家族苗族自治州");
		courtCity.put("恩施市人民法院","恩施土家族苗族自治州");
		courtCity.put("利川市人民法院","恩施土家族苗族自治州");
		courtCity.put("建始县人民法院","恩施土家族苗族自治州");
		courtCity.put("巴东县人民法院","恩施土家族苗族自治州");
		courtCity.put("宣恩县人民法院","恩施土家族苗族自治州");
		courtCity.put("咸丰县人民法院","恩施土家族苗族自治州");
		courtCity.put("来凤县人民法院","恩施土家族苗族自治州");
		courtCity.put("鹤峰县人民法院","恩施土家族苗族自治州");
		courtCity.put("恩施州咸丰县人民法院","恩施土家族苗族自治州");
		courtCity.put("恩施州巴东县人民法院","恩施土家族苗族自治州");
		courtCity.put("恩施州建始县人民法院","恩施土家族苗族自治州");
		courtCity.put("恩施州宣恩县人民法院","恩施土家族苗族自治州");
		courtCity.put("恩施州鹤峰县人民法院","恩施土家族苗族自治州");
		courtCity.put("湖北省汉江中级人民法院","仙桃市");
		courtCity.put("仙桃市人民法院","仙桃市");
		courtCity.put("潜江市人民法院","潜江市");
		courtCity.put("天门市人民法院","天门市");
		courtCity.put("武汉铁路运输中级法院","武汉市");
		courtCity.put("武汉铁路运输法院","武汉市");
		courtCity.put("襄阳铁路运输法院","武汉市");
		courtCity.put("武汉海事法院","武汉市");
		courtCity.put("荆门市沙洋县人民法院","荆门市");
		courtCity.put("十堰市丹江口市人民法院","十堰市");
		courtCity.put("十堰市竹溪县人民法院","十堰市");
		courtCity.put("十堰市郧西县人民法院","十堰市");
		courtCity.put("宜昌市葛洲坝人民法院","宜昌市");
		courtCity.put("黄石市中级人民法院","黄石市");
		courtCity.put("荆州市石首市人民法院","荆州市");
		courtCity.put("十堰市中级人民法院","十堰市");
		courtCity.put("孝感市大悟县人民法院","孝感市");
		courtCity.put("孝感市云梦县人民法院","孝感市");
		courtCity.put("襄阳市老河口市人民法院","襄阳市");
		courtCity.put("随州市中级人民法院","随州市");
		courtCity.put("宜昌市中级人民法院","宜昌市");
		courtCity.put("宜昌市兴山县人民法院","宜昌市");
		courtCity.put("宜昌市枝江市人民法院","宜昌市");
		courtCity.put("黄冈市红安县人民法院","黄冈市");
		courtCity.put("咸宁市崇阳县人民法院","咸宁市");
		courtCity.put("咸宁市通山县人民法院","咸宁市");
		courtCity.put("黄冈市蕲春县人民法院","黄冈市");
		courtCity.put("孝感市安陆市人民法院","孝感市");
		courtCity.put("黄石市大冶市人民法院","黄石市");
		courtCity.put("宜昌市远安县人民法院","宜昌市");
		courtCity.put("荆州市松滋市人民法院","荆州市");
		courtCity.put("黄冈市武穴市人民法院","黄冈市");
		courtCity.put("黄冈市麻城市人民法院","黄冈市");
		courtCity.put("宜昌市宜都市人民法院","宜昌市");
		courtCity.put("武汉市东湖新技术开发区人民法院","武汉市");
		courtCity.put("襄阳市南漳县人民法院","襄阳市");
		courtCity.put("襄阳市枣阳市人民法院","襄阳市");
		courtCity.put("黄冈市浠水县人民法院","黄冈市");
		courtCity.put("恩施州利川市人民法院","恩施土家族苗族自治州");
		courtCity.put("黄冈市英山县人民法院","黄冈市");
		courtCity.put("黄石市阳新县人民法院","黄石市");
		courtCity.put("孝感市应城市人民法院","孝感市");
		courtCity.put("宜昌市秭归县人民法院","宜昌市");
		courtCity.put("襄阳市宜城市人民法院","襄阳市");
		courtCity.put("随州市广水市人民法院","随州市");
		courtCity.put("咸宁市赤壁市人民法院","咸宁市");
		courtCity.put("荆门市沙洋人民法院","荆门市");
		courtCity.put("荆门市钟祥市人民法院","荆门市");
		courtCity.put("荆州市洪湖市人民法院","荆州市");
		courtCity.put("襄阳市高新技术开发区人民法院","襄阳市");
		courtCity.put("黄冈市罗田县人民法院","黄冈市");
		courtCity.put("恩施州来凤县人民法院","恩施土家族苗族自治州");
		courtCity.put("荆州市中级人民法院","荆州市");
		courtCity.put("荆门市京山县人民法院","荆门市");
		courtCity.put("襄阳市谷城县人民法院","襄阳市");
		courtCity.put("咸宁市嘉鱼县人民法院","咸宁市");
		courtCity.put("咸宁市通城县人民法院","咸宁市");
		courtCity.put("宜昌市当阳市人民法院","宜昌市");
		courtCity.put("孝感市中级人民法院","孝感市");
		courtCity.put("十堰市房县人民法院","十堰市");
		courtCity.put("恩施州恩施市人民法院","恩施土家族苗族自治州");
		courtCity.put("黄冈市团风县人民法院","黄冈市");
		courtCity.put("黄冈市黄梅县人民法院","黄冈市");
		courtCity.put("荆州市公安县人民法院","荆州市");
		courtCity.put("荆门市中级人民法院","荆门市");
		courtCity.put("孝感市孝昌县人民法院","孝感市");
		courtCity.put("荆州市监利县人民法院","荆州市");
		courtCity.put("十堰市竹山县人民法院","十堰市");
		courtCity.put("湖北省随县人民法院","随州 市");
		courtCity.put("宜昌市五峰土家族自治县人民法院","宜昌市");
		courtCity.put("荆州市江陵县人民法院","荆州市");
		courtCity.put("襄阳市保康县人民法院","襄阳市");
		courtCity.put("孝感市汉川市人民法院","孝感市");
		courtCity.put("宜昌市长阳土家族自治县人民法院","宜昌市");
		courtCity.put("荆州市监利县人民法院","荆州市");
		courtCity.put("恩施土家族苗族自治州中级人民法院","恩施土家族苗族自治州");
		courtCity.put("吉安市万安县人民法院","吉安市");
		courtCity.put("上饶市万年县人民法院","上饶市");
		courtCity.put("宜春市万载县人民法院","宜春市");
		courtCity.put("萍乡市上栗县人民法院","萍乡市");
		courtCity.put("赣州市上犹县人民法院","赣州市");
		courtCity.put("上饶市上饶县人民法院","上饶市");
		courtCity.put("上饶市信州区人民法院","上饶市");
		courtCity.put("上饶市广丰区人民法院","上饶市");
		courtCity.put("江西省高级人民法院","南昌市");
		courtCity.put("南昌市高新技术产业开发区人民法院","南昌市");
		courtCity.put("南昌市安义县人民法院","南昌市");
		courtCity.put("赣州市赣县区人民法院","赣州市");
		courtCity.put("南昌市经济技术开发区人民法院","南昌市");
		courtCity.put("宜春市上高县人民法院","宜春市");
		courtCity.put("抚州市东乡县人民法院","抚州市");
		courtCity.put("宜春市丰城市人民法院","宜春市");
		courtCity.put("抚州市乐安县人民法院","抚州市");
		courtCity.put("景德镇市乐平市人民法院","景德镇市");
		courtCity.put("九江市九江县人民法院","九江市");
		courtCity.put("九江市庐山区人民法院","九江市");
		courtCity.put("九江市浔阳区人民法院","九江市");
		courtCity.put("赣州市于都县人民法院","赣州市");
		courtCity.put("吉安市井冈山市人民法院","吉安市");
		courtCity.put("赣州市会昌县人民法院","赣州市");
		courtCity.put("赣州市会昌县人民法院","赣州市");
		courtCity.put("上饶市余干县人民法院","上饶市");
		courtCity.put("鹰潭市余江县人民法院","鹰潭市");
		courtCity.put("赣州市信丰县人民法院","赣州市");
		courtCity.put("九江市修水县人民法院","九江市");
		courtCity.put("赣州市全南县人民法院","赣州市");
		courtCity.put("九江市共青城市人民法院","九江市");
		courtCity.put("赣州市兴国县人民法院","赣州市");
		courtCity.put("新余市分宜县人民法院","新余市");
		courtCity.put("抚州市南丰县人民法院","抚州市");
		courtCity.put("抚州市南城县人民法院","抚州市");
		courtCity.put("南昌市南昌县人民法院","南昌市");
		courtCity.put("南昌市东湖区人民法院","南昌市");
		courtCity.put("南昌市湾里区人民法院","南昌市");
		courtCity.put("南昌市西湖区人民法院","南昌市");
		courtCity.put("南昌市青云谱区人民法院","南昌市");
		courtCity.put("南昌市青山湖区人民法院","南昌市");
		courtCity.put("南昌经济技术开发区人民法院","南昌市");
		courtCity.put("南昌铁路运输中级法院","南昌市");
		courtCity.put("南昌铁路运输法院","南昌市");
		courtCity.put("南昌高新技术产业开发区人民法院","南昌市");
		courtCity.put("吉安市吉安县人民法院","吉安市");
		courtCity.put("吉安市吉州区人民法院","吉安市");
		courtCity.put("吉安市青原区人民法院","吉安市");
		courtCity.put("吉安市吉水县人民法院","吉安市");
		courtCity.put("赣州市大余县人民法院","赣州市");
		courtCity.put("宜春市奉新县人民法院","宜春市");
		courtCity.put("上饶市婺源县人民法院","上饶市");
		courtCity.put("宁都县人民法院","赣州市");
		courtCity.put("赣州市宁都县人民法院","赣州市");
		courtCity.put("安义县人民法院","南昌市");
		courtCity.put("吉安市安福县人民法院","吉安市");
		courtCity.put("安远县人民法院","赣州市");
		courtCity.put("赣州市安远县人民法院","赣州市");
		courtCity.put("赣州市定南县人民法院","赣州市");
		courtCity.put("宜春市宜丰县人民法院","宜春市");
		courtCity.put("宜春市袁州区人民法院","宜春市");
		courtCity.put("抚州市宜黄县人民法院","抚州市");
		courtCity.put("赣州市寻乌县人民法院","赣州市");
		courtCity.put("吉安市峡江县人民法院","吉安市");
		courtCity.put("赣州市崇义县人民法院","赣州市");
		courtCity.put("赣州市崇义县人民法院","赣州市");
		courtCity.put("抚州市崇仁县人民法院","抚州市");
		courtCity.put("抚州市广昌县人民法院","抚州市");
		courtCity.put("九江市庐山人民法院","九江市");
		courtCity.put("上饶市弋阳县人民法院","上饶市");
		courtCity.put("九江市彭泽县人民法院","九江市");
		courtCity.put("上饶市德兴市人民法院","上饶市");
		courtCity.put("九江市德安县人民法院","九江市");
		courtCity.put("抚州市临川区人民法院","抚州市");
		courtCity.put("新余市渝水区人民法院","新余市");
		courtCity.put("吉安市新干县人民法院","吉安市");
		courtCity.put("南昌市新建县人民法院","南昌市");
		courtCity.put("南昌市新建县人民法院","南昌市");
		courtCity.put("九江市星子县人民法院","九江市");
		courtCity.put("景德镇市昌江区人民法院","景德镇市");
		courtCity.put("景德镇市珠山区人民法院","景德镇市");
		courtCity.put("樟树市人民法院","宜春市");
		courtCity.put("宜春市樟树市人民法院","宜春市");
		courtCity.put("上饶市横峰县人民法院","上饶市");
		courtCity.put("九江市武宁县人民法院","九江市");
		courtCity.put("吉安市永丰县人民法院","吉安市");
		courtCity.put("九江市永修县人民法院","九江市");
		courtCity.put("吉安市永新县人民法院","吉安市");
		courtCity.put("江西省上饶市中级人民法院","上饶市");
		courtCity.put("江西省九江市中级人民法院","九江市");
		courtCity.put("江西省南昌市中级人民法院","南昌市");
		courtCity.put("江西省吉安市中级人民法院","吉安市");
		courtCity.put("江西省宜春市中级人民法院","宜春市");
		courtCity.put("江西省抚州市中级人民法院","抚州市");
		courtCity.put("江西省新余市中级人民法院","新余市");
		courtCity.put("江西省景德镇市中级人民法院","景德镇市");
		courtCity.put("江西省萍乡市中级人民法院","萍乡市");
		courtCity.put("江西省赣州市中级人民法院","赣州市");
		courtCity.put("上饶市中级人民法院","上饶市");
		courtCity.put("九江市中级人民法院","九江市");
		courtCity.put("南昌市中级人民法院","南昌市");
		courtCity.put("吉安市中级人民法院","吉安市");
		courtCity.put("宜春市中级人民法院","宜春市");
		courtCity.put("抚州市中级人民法院","抚州市");
		courtCity.put("新余市中级人民法院","新余市");
		courtCity.put("景德镇市中级人民法院","景德镇市");
		courtCity.put("鹰潭市中级人民法院","鹰潭市");
		courtCity.put("萍乡市中级人民法院","萍乡市");
		courtCity.put("赣州市中级人民法院","赣州市");
		courtCity.put("高级人民法院","南昌市");
		courtCity.put("江西省鹰潭市中级人民法院","鹰潭市");
		courtCity.put("吉安市泰和县人民法院","吉安市");
		courtCity.put("景德镇市浮梁县人民法院","景德镇市");
		courtCity.put("九江市湖口县人民法院","九江市");
		courtCity.put("上饶市玉山县人民法院","上饶市");
		courtCity.put("九江市瑞昌市人民法院","九江市");
		courtCity.put("赣州市瑞金市人民法院","赣州市");
		courtCity.put("赣州市石城县人民法院","赣州市");
		courtCity.put("萍乡市芦溪县人民法院","萍乡市");
		courtCity.put("萍乡市莲花县人民法院","萍乡市");
		courtCity.put("萍乡市安源区人民法院","萍乡市");
		courtCity.put("萍乡市湘东区人民法院","萍乡市");
		courtCity.put("鹰潭市贵溪市人民法院","鹰潭市");
		courtCity.put("抚州市资溪县人民法院","抚州市");
		courtCity.put("抚州市资溪县人民法院","抚州市");
		courtCity.put("赣州市赣县人民法院","赣州市");
		courtCity.put("赣州市南康区人民法院","赣州市");
		courtCity.put("赣州市章贡区人民法院","赣州市");
		courtCity.put("赣州经济技术开发区人民法院","赣州市");
		courtCity.put("南昌市进贤县人民法院","南昌市");
		courtCity.put("吉安市遂川县人民法院","吉安市");
		courtCity.put("九江市都昌县人民法院","九江市");
		courtCity.put("上饶市鄱阳县人民法院","上饶市");
		courtCity.put("抚州市金溪县人民法院","抚州市");
		courtCity.put("上饶市铅山县人民法院","上饶市");
		courtCity.put("宜春市铜鼓县人民法院","宜春市");
		courtCity.put("宜春市靖安县人民法院","宜春市");
		courtCity.put("宜春市高安市人民法院","宜春市");
		courtCity.put("鹰潭市月湖区人民法院","鹰潭市");
		courtCity.put("抚州市黎川县人民法院","抚州市");
		courtCity.put("赣州市龙南县人民法院","赣州市");	
		courtCity.put("赣州市龙南县人民法院","赣州市");	
		courtCity.put("九江市濂溪区人民法院","九江市");
		courtCity.put("九江市庐山市人民法院","九江市");
	}
	static HashMap<String,String> areaCourt=new HashMap<String,String>();
	static
	{
		areaCourt.put("东兴","内江市东兴区人民法院");
		areaCourt.put("北川","北川县人民法院");
		areaCourt.put("安县","安县人民法院");
		areaCourt.put("高院","四川省高级人民法院");
		areaCourt.put("广汉","广汉市人民法院");
		areaCourt.put("锦江","成都市锦江区人民法院");
		areaCourt.put("武侯","成都市武侯区人民法院");
		areaCourt.put("成华","成都市成华区人民法院");
		areaCourt.put("新都","新都区人民法院");
		areaCourt.put("金堂","金堂县人民法院");
		areaCourt.put("双流","双流县人民法院");
		areaCourt.put("都江堰","都江堰市人民法院");
		areaCourt.put("邛崃","邛崃市人民法院");
		areaCourt.put("成都高新技术产业开发","成都高新技术产业开发区人民法院");
		areaCourt.put("成都","成都市中级人民法院");
		areaCourt.put("东区","攀枝花市东区人民法院");
		areaCourt.put("江阳","泸州市江阳区人民法院");
		areaCourt.put("合江","合江县人民法院");
		areaCourt.put("叙永","叙永县人民法院");
		areaCourt.put("古蔺","古蔺县人民法院");
		areaCourt.put("旌阳","德阳市旌阳区人民法院");
		areaCourt.put("中江","中江县人民法院");
		areaCourt.put("什邡","什邡县人民法院");
		areaCourt.put("绵竹","绵竹市人民法院");
		areaCourt.put("三台","三台县人民法院");
		areaCourt.put("江油","江油市人民法院");
		areaCourt.put("苍溪","苍溪县人民法院");
		areaCourt.put("船山","遂宁市船山区人民法院");
		areaCourt.put("市中","内江市市中区人民法院");
		areaCourt.put("威远","威远县人民法院");
		areaCourt.put("资中","资中县人民法院");
		areaCourt.put("隆昌","隆昌县人民法院");
		areaCourt.put("峨眉山","峨眉山市人民法院");
		areaCourt.put("顺庆","南充市顺庆区人民法院");
		areaCourt.put("高坪","南充市高坪区人民法院");
		areaCourt.put("嘉陵","南充市嘉陵区人民法院");
		areaCourt.put("南部","南部县人民法院");
		areaCourt.put("西充","西充县人民法院");
		areaCourt.put("南充","南充市中级人民法院");
		areaCourt.put("仁寿","仁寿县人民法院");
		areaCourt.put("广安","广安市中级人民法院");
		areaCourt.put("广安","广安市广安区人民法院");
		areaCourt.put("岳池","岳池县人民法院");
		areaCourt.put("邻水","邻水县人民法院");
		areaCourt.put("大竹","大竹县人民法院");
		areaCourt.put("渠县","渠县人民法院");
		areaCourt.put("万源","万源市人民法院");
		areaCourt.put("雨城","雅安市雨城区人民法院");
		areaCourt.put("巴州","巴州市巴中区人民法院");
		areaCourt.put("雁江","资阳市雁江区人民法院");
		areaCourt.put("安岳","安岳县人民法院");
		areaCourt.put("西昌","西昌市人民法院");
		areaCourt.put("会理","会理县人民法院");
		areaCourt.put("青羊","成都市青羊区人民法院");
		areaCourt.put("金牛","成都市金牛区人民法院");
		areaCourt.put("龙泉驿","成都市龙泉驿区人民法院");
		areaCourt.put("青白江","成都市青白江区人民法院");
		areaCourt.put("温江","成都市温江区人民法院");
		areaCourt.put("郫县","郫县人民法院");
		areaCourt.put("大邑","大邑县人民法院");
		areaCourt.put("蒲江","蒲江县人民法院");
		areaCourt.put("新津","新津县人民法院");
		areaCourt.put("简阳","简阳市人民法院");
		areaCourt.put("彭州","彭州市人民法院");
		areaCourt.put("崇州","崇州市人民法院");
		areaCourt.put("自贡","自贡市中级人民法院");
		areaCourt.put("西区","攀枝花市西区人民法院");
		areaCourt.put("仁和","攀枝花市仁和区人民法院");
		areaCourt.put("米易","米易县人民法院");
		areaCourt.put("盐边","盐边县人民法院");
		areaCourt.put("攀枝花","攀枝花市中级人民法院");
		areaCourt.put("纳溪","泸州市纳溪区人民法院");
		areaCourt.put("龙马潭","泸州市龙马潭区人民法院");
		areaCourt.put("泸州","泸州市中级人民法院");
		areaCourt.put("罗江","罗江县人民法院");
		areaCourt.put("德阳","德阳市中级人民法院");
		areaCourt.put("涪城","绵阳市培城区人民法院");
		areaCourt.put("游仙","绵阳市游仙区人民法院");
		areaCourt.put("盐亭","盐亭县人民法院");
		areaCourt.put("梓潼","梓潼县人民法院");
		areaCourt.put("平武","平武县人民法院");
		areaCourt.put("高新技术产业开","绵阳市高新技术产业开发区人民法院");
		areaCourt.put("绵阳","绵阳市中级人民法院");
		areaCourt.put("利州","广元市利州区人民法院");
		areaCourt.put("元坝","广元市昭化区人民法院");
		areaCourt.put("朝天","广元市朝天区人民法院");
		areaCourt.put("旺苍","旺苍县人民法院");
		areaCourt.put("青川","青川县人民法院");
		areaCourt.put("剑阁","剑阁县人民法院");
		areaCourt.put("广元","广元市中级人民法院");
		areaCourt.put("安居","遂宁市安居区人民法院");
		areaCourt.put("蓬溪","蓬溪县人民法院");
		areaCourt.put("射洪","射洪县人民法院");
		areaCourt.put("大英","大英县人民法院");
		areaCourt.put("遂宁","遂宁市中级人民法院");
		areaCourt.put("内江","内江市中级人民法院");
		areaCourt.put("沙湾","乐山市沙湾区人民法院");
		areaCourt.put("五通桥","乐山市五通桥区人民法院");
		areaCourt.put("金口河","乐山市金口河区人民法院");
		areaCourt.put("犍为","犍为县人民法院");
		areaCourt.put("井研","井研县人民法院");
		areaCourt.put("夹江","夹江县人民法院");
		areaCourt.put("沐川","沐川县人民法院");
		areaCourt.put("峨边彝族","峨边彝族自治县人民法院");
		areaCourt.put("马边彝族","马边彝族自治县人民法院");
		areaCourt.put("乐山","乐山市中级人民法院");
		areaCourt.put("营山","营山县人民法院");
		areaCourt.put("蓬安","蓬安县人民法院");
		areaCourt.put("仪陇","仪陇县人民法院");
		areaCourt.put("阆中","阆中市人民法院");
		areaCourt.put("东坡","眉山市东坡区人民法院");
		areaCourt.put("彭山","彭山县人民法院");
		areaCourt.put("洪雅","洪雅县人民法院");
		areaCourt.put("眉山","眉山市中级人民法院");
		areaCourt.put("翠屏","宜宾市翠屏区人民法院");
		areaCourt.put("南溪区","南溪县人民法院");
		areaCourt.put("宜宾","宜宾市中级人民法院");
		areaCourt.put("宜宾","宜宾县人民法院");
		areaCourt.put("江安","江安县人民法院");
		areaCourt.put("长宁","长宁县人民法院");
		areaCourt.put("高县","高县人民法院");
		areaCourt.put("珙县","珙县人民法院");
		areaCourt.put("筠连","筠连县人民法院");
		areaCourt.put("兴文","兴文县人民法院");
		areaCourt.put("屏山","屏山县人民法院");
		areaCourt.put("前锋","前锋区人民法院");
		areaCourt.put("武胜","武胜县人民法院");
		areaCourt.put("华蓥","华蓥市人民法院");
		areaCourt.put("通川","达州市通川区人民法院");
		areaCourt.put("达","达县人民法院");
		areaCourt.put("宣汉","宣汉县人民法院");
		areaCourt.put("开江","开江县人民法院");
		areaCourt.put("达州","达州市中级人民法院");
		areaCourt.put("名山","名山县人民法院");
		areaCourt.put("荥经","荥经县人民法院");
		areaCourt.put("汉源","汉源县人民法院");
		areaCourt.put("石棉","石棉县人民法院");
		areaCourt.put("天全","天全县人民法院");
		areaCourt.put("芦山","芦山县人民法院");
		areaCourt.put("宝兴","宝兴县人民法院");
		areaCourt.put("雅安","雅安市中级人民法院");
		areaCourt.put("恩阳","巴中市恩阳区人民法院");
		areaCourt.put("通江","通江县人民法院");
		areaCourt.put("南江","南江县人民法院");
		areaCourt.put("平昌","平昌县人民法院");
		areaCourt.put("巴中","巴中市中级人民法院");
		areaCourt.put("乐至","乐至县中级人民法院");
		areaCourt.put("资阳","资阳市中级人民法院");
		areaCourt.put("马尔康","马尔康县人民法院");
		areaCourt.put("汶川","汶川县人民法院");
		areaCourt.put("理县","理县人民法院");
		areaCourt.put("茂县","茂县人民法院");
		areaCourt.put("松潘","松潘县人民法院");
		areaCourt.put("九寨沟","九寨沟县人民法院");
		areaCourt.put("金川","金川县人民法院");
		areaCourt.put("小金","小金县人民法院");
		areaCourt.put("黑水","黑水县人民法院");
		areaCourt.put("壤塘","壤塘县人民法院");
		areaCourt.put("阿坝","阿坝藏族羌族自治州人民法院");
		areaCourt.put("阿坝","阿坝县人民法院");
		areaCourt.put("若尔盖","若尔盖县人民法院");
		areaCourt.put("红原","红原县人民法院");
		areaCourt.put("康定","康定县人民法院");
		areaCourt.put("泸定","泸定县人民法院");
		areaCourt.put("丹巴","丹巴县人民法院");
		areaCourt.put("九龙","九龙县人民法院");
		areaCourt.put("雅江","雅江县人民法院");
		areaCourt.put("道孚","道孚县人民法院");
		areaCourt.put("炉霍","炉霍县人民法院");
		areaCourt.put("甘孜","甘孜藏族自治州中级人民法院");
		areaCourt.put("德格","德格县人民法院");
		areaCourt.put("白玉","白玉县人民法院");
		areaCourt.put("色达","色达县人民法院");
		areaCourt.put("理塘","理塘县人民法院");
		areaCourt.put("巴塘","巴塘县人民法院");
		areaCourt.put("乡城","乡城县人民法院");
		areaCourt.put("稻城","稻城县人民法院");
		areaCourt.put("得荣","得荣县人民法院");
		areaCourt.put("木里藏族","木里藏族自治县人民法院");
		areaCourt.put("盐源","盐源县人民法院");
		areaCourt.put("德昌","德昌县人民法院");
		areaCourt.put("会东","会东县人民法院");
		areaCourt.put("宁南","宁南县人民法院");
		areaCourt.put("普格","普格县人民法院");
		areaCourt.put("布拖","布拖县人民法院");
		areaCourt.put("金阳","金阳县人民法院");
		areaCourt.put("昭觉","昭觉县人民法院");
		areaCourt.put("喜德","喜德县人民法院");
		areaCourt.put("冕宁","冕宁县人民法院");
		areaCourt.put("越西","越西县人民法院");
		areaCourt.put("甘洛","甘洛县人民法院");
		areaCourt.put("美姑","美姑县人民法院");
		areaCourt.put("雷波","雷波县人民法院");
		areaCourt.put("凉山","凉山彝族自治州中级人民法院");
		areaCourt.put("成都铁路","成都铁路运输法院");
		areaCourt.put("西昌铁路","西昌铁路运输法院");
		areaCourt.put("成铁","成都铁路运输中级人民法院");
		areaCourt.put("514003","贵阳铁路运输法院");
		areaCourt.put("四川省高级人民法院","四川省高级人民法院");
		areaCourt.put("泸县","泸县人民法院");
		areaCourt.put("新龙","新龙县人民法院");
		areaCourt.put("石渠","石渠县人民法院");
		areaCourt.put("","四川省科学城人民法院");
	}
	
	public String getSelectCmd() throws IOException
	{
		File src=new File("conf/notice_type1.sql");
		FileInputStream reader = new FileInputStream(src);
		int l=(int) src.length();
		byte[] content=new byte[l];
		reader.read(content);
		reader.close();
		String selectCmd=new String(content);
		System.out.println(selectCmd);
		selectCmd=selectCmd.replace("@start_dt", "'"+startDt+"'");
		selectCmd=selectCmd.replace("@stop_dt", "'"+stopDt+"'");
//		System.out.println(selectCmd.length()-100);
		System.out.println(selectCmd);
		return selectCmd;
	}
	
	public void run(JobConfig jobConf) throws ClassNotFoundException, SQLException, IOException, ParseException, InterruptedException
	{
		if(jobConf.hasProperty("startDt"))
		{
			startDt=jobConf.getString("startDt");
		}
		if(jobConf.hasProperty("stopDt"))
		{
			stopDt=jobConf.getString("stopDt");
		}
		String dt=TimeUtils.dateAdd(stopDt, -1);
//		File f=new File("data/notice_type1_"+startDt+"_"+stopDt+".txt");
		File dir=new File("datafile/"+TimeUtils.getYesterday());
		if(!dir.exists())
		{
			dir.mkdirs();
		}
		
		File f=new File(dir.getAbsolutePath()+"/notice_type1.txt");
		FileWriter fw=new FileWriter(f);
		String path = f.getAbsolutePath();
		String selectCmd=getSelectCmd();
		System.out.println(selectCmd);
		Pattern pattern1 = Pattern.compile("\\s");
		
		int jobStatus1=0;
		String remark1="";
		
		try
		{
			ResultSet result = MySQL.executeQuery(selectCmd);
			int cnt=0;
			while(result.next())
			{
				String anYou=pattern1.matcher(result.getString("an_you")).replaceAll("");
				String anHao=pattern1.matcher(result.getString("an_hao")).replaceAll("");
				anHao=anHao.replace("(", "（").replace(")", "）");
				String faYuanMingCheng=pattern1.matcher(result.getString("fa_yuan_ming_cheng")).replaceAll("");
				String shenLiFaTing=pattern1.matcher(result.getString("shen_li_fa_ting")).replaceAll("");
				String zhuShenFaGuan=pattern1.matcher(result.getString("zhu_shen_fa_guan")).replaceAll("");
				String chengBanTing=pattern1.matcher(result.getString("cheng_ban_ting")).replaceAll("");
				String dangShiRen=pattern1.matcher(result.getString("dang_shi_ren")).replaceAll("");
				String province=pattern1.matcher(result.getString("province")).replaceAll("");
				String city=pattern1.matcher(result.getString("city")).replaceAll("");
				String kaiTingRiQi=result.getString("kai_ting_ri_qi");
				
				dangShiRen=pattern.matcher(dangShiRen).replaceAll("");
				if (city.equals("合肥市"))
				{
					Matcher m2 = pattern2.matcher(kaiTingRiQi);
					if (m2.find()) {
						kaiTingRiQi=m2.group();        
			        }
				}
//				System.out.println("dangShiRen:"+dangShiRen);
				kaiTingRiQi=ParseDate.parse(kaiTingRiQi);	
				if (city.equals("不确定"))
				{		
					city=courtCity.get(faYuanMingCheng);
//					System.out.println(faYuanMingCheng);
//					System.out.println(province+"--------"+city);		
							
//					Iterator<Entry<String, String>> iterator= courtCity.entrySet().iterator();
//					while(iterator.hasNext())
//					{
//						System.out.println(courtCity.get(faYuanMingCheng));
//						Entry<String, String> entry = iterator.next();
//						String desc=entry.getKey();
//						String val=entry.getValue();
//						System.out.println("desc:"+desc);
//						System.out.println("val:"+val);
//						System.out.println("faYuanMingCheng:"+faYuanMingCheng);
//						if (faYuanMingCheng.equals(desc))
//						{
//							city=val;
//							System.out.println(province+"--------"+city);		
//							break;
//						}
										
//					}
				}
				if (province.equals("四川省"))
				{
					faYuanMingCheng=areaCourt.get(faYuanMingCheng);
					if (faYuanMingCheng==null)
					{
						System.out.println("dangShiRen:"+dangShiRen);
					}
					else
					{
						if (faYuanMingCheng.equals("内江市市中区人民法院") && !(shenLiFaTing.equals("511002002")))
						{
							city="乐山市";
							faYuanMingCheng="乐山市市中区人民法院";
						}

						if (faYuanMingCheng.equals("贵阳铁路运输法院"))
						{
							province="贵州省";
						}
					}
					
				}
				
				dangShiRen=dangShiRen.replace("原审第三人", "").replace("第三人", "").replace("()", "")
						.replace("；", ";").replace("：", ":").replace(";:", ";").replace(";;", ";").replace(",:", ",").replace(":;", ";");
				if(dangShiRen.startsWith(":") || dangShiRen.startsWith(";"))
				{
					dangShiRen=dangShiRen.substring(1,dangShiRen.length());
				}
				String outLine1=kaiTingRiQi+"\001"+anYou+"\001"+anHao+"\001"
						+faYuanMingCheng+"\001"+shenLiFaTing+"\001"
						+zhuShenFaGuan+"\001"+chengBanTing+"\001"+dangShiRen+"\001"
						+province+"\001"+city;
				String outLine2=kaiTingRiQi+"\001"+anYou+"\001"+anHao+"\001"
						+faYuanMingCheng+"\001"+shenLiFaTing+"\001"
						+zhuShenFaGuan+"\001"+chengBanTing+"\001"+dangShiRen;
				String md5=DigestUtils.md5Hex(outLine2);
								
				String[] companyArr=dangShiRen.split("[;,；:：，、与诉及]");
				for(String company:companyArr)
				{
					if(!(company.contains("原告")
							|| company.contains("被告")
							|| company.contains("被上诉人")
							|| company.contains("上诉人")
							|| company.isEmpty()
							|| company.contains("null")
//							|| company.contains("集团")
//							|| company.contains("企业")
//							|| company.contains("超市")
//							|| company.contains("有限合伙")
//							|| company.contains("公司")
//							|| (company.length()>5 && (
//									company.endsWith("厂")
//									|| company.endsWith("社")
//									|| company.endsWith("场")
//									|| company.endsWith("店")
//									|| company.endsWith("行")
//									|| company.endsWith("部")							
//								))
							))
					{						
						company=company.replace("(", "（").replace(")", "）");
						String key=company+"_"+tableId+"_"+md5;
						String outLine=key+"\001"+company+"\001"+outLine1+"\n";
//						System.out.println(outLine);												
						fw.write(outLine);
					}
				}
				if((++cnt)%1000==0)
				{
					System.out.println("++"+cnt);
				}
			}
			fw.close();
		}
		catch (Exception e)
		{
			e.printStackTrace();
			remark1=SysFunc.getError(e);
			jobStatus1=1;
		}

		WriteJobStatus.writeJobStatus("开庭公告解析（类型1）", dt, jobStatus1, remark1.replace("'", ""));
//		String[] args=new String[]
//				{"hive"
//				,"-e"
//				,String.format("\"LOAD DATA LOCAL INPATH '%s' into TABLE ods.kai_ting_gong_gao partition(dt='%s')\"",path,dt)
//				};
//		int jobStatus2=0;
//		String remark2="";
//		try
//		{
//			remark2=ExecShell.exec(args);
//		}
//		catch (Exception e)
//		{
//			remark2=SysFunc.getError(e);
//			jobStatus2=1;
//		}
//		WriteJobStatus.writeJobStatus("开庭公告导入hive（类型1）", dt, jobStatus2, remark2.replace("'", ""));
//		String[] load2HbaseArgs=new String[]
//				{"sh"
//				,"/home/likai/ImportCourtNoticeToHbase.sh"
//				,dt
//				};
//		int jobStatus3=0;
//		String remark3="";
//		try
//		{
//			remark3=ExecShell.exec(load2HbaseArgs);
//		}
//		catch (Exception e)
//		{
//			remark3=SysFunc.getError(e);
//			jobStatus3=1;
//		}
//		WriteJobStatus.writeJobStatus("开庭公告导入hbase（类型1）", dt, jobStatus3, remark3.replace("'", ""));
	}
	
	public static void main(String[] args) throws ClassNotFoundException, SQLException, IOException, ParseException, InterruptedException
	{
		String[] newArgs={"--startDt=2017-08-06","--stopDt=2017-08-07"};
		JobConfig jobConf=new JobConfig(newArgs);
		CourtNoticeType1Job job =new CourtNoticeType1Job();
//		job.getSelectCmd();
		job.run(jobConf);
	}
}
